---
# This role will create the database far Dependecy Track and configure PostgresSQL.

- name: Installation of PostgreSQL database adapter for Python
  yum:
    name: 
      - python-psycopg2
      - python-ipaddress
    state: present

- name: Create app database
  postgresql_db:
    state: present
    name: "{{db_name}}"
  become: yes
  become_user: postgres

- name: Create db user
  postgresql_user:
    state: present
    name: "{{db_user}}"
    password: "{{db_pwd}}"
  become: yes
  become_user: postgres

- name: Grant db user access to app db
  postgresql_privs:
    type: database
    database: "{{db_name}}"
    roles: "{{db_user}}"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres

- name: Allow md5 connection for the db user
  postgresql_pg_hba:
    dest: "/var/lib/pgsql/{{postgresql_version}}/data/pg_hba.conf"
    contype: host
    databases: "{{db_name}}"
    method: md5
    users: "{{db_user}}"
    create: true
  become: yes
  become_user: postgres
  notify: Restart postgres service