---
# This role will install PostgreSQL
# Source : https://www.postgresql.org/download/linux/redhat/

- name: Install the repository rpm
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install PostgreSQL
  yum:
    name: "postgresql{{postgresql_version}}-server"
    state: present

- name: Find out if PostgreSQL is initialized
  stat:
    path: "/var/lib/pgsql/{{postgresql_version}}/data/pg_hba.conf"
  register: postgres_data

- name: Initialize PostgreSQL
  shell: "postgresql-{{postgresql_version}}-setup initdb"
  when: not postgres_data.stat.exists

- name: Enable and start PostgreSQL service
  systemd:
    name: "postgresql-{{postgresql_version}}"
    state: started
    enabled: yes